version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${TWITTER_DB_USER}
      - POSTGRES_PASSWORD=${TWITTER_DB_PASSWORD}
      - POSTGRES_DB=${TWITTER_DB_NAME}
    ports:
      - '${TWITTER_DB_HOST}:5432'